name: update
on: [workflow_dispatch]
jobs:
  update:
    runs-on: windows-latest
    steps:
      - uses: MinoruSekine/setup-scoop@v1
      - run: '"%USERPROFILE%\scoop\apps\scoop\current\bin\checkver.ps1" -App * -Dir bucket'
        shell: powershell
