name: update
on: [workflow_dispatch]
jobs:
  update:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: MinoruSekine/setup-scoop@v1
      - run: 'Invoke-Expression "$env:USERPROFILE\scoop\apps\scoop\current\bin\checkver.ps1 -App * -Dir bucket -U"'
        shell: powershell
